# Generated by Django 3.1.1 on 2020-10-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('occupation', models.CharField(max_length=64)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('relation_to_student', models.CharField(max_length=32)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateTimeField()),
                ('place_of_birth', models.CharField(blank=True, max_length=64)),
                ('hometown', models.CharField(blank=True, max_length=64)),
                ('home_address', models.CharField(blank=True, max_length=128)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to=students.models.student_image_file_path)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('guardians', models.ManyToManyField(related_name='students', to='students.Guardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school')),
            ],
        ),
    ]
