# Generated by Django 3.1.1 on 2020-10-11 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='mobile_no',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='mobile_phone',
        ),
        migrations.AddField(
            model_name='guardian',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
