# Generated by Django 3.1.1 on 2020-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grade_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='programmes',
            field=models.ManyToManyField(related_name='schools', to='core.Programme'),
        ),
    ]
